//! Auto-generated module
//!
//! 🤖 Generated with [SplitRS](https://github.com/cool-japan/splitrs)

use std::io::{BufWriter, Write};
use std::path::Path;

use super::types::{
    PlyError, PlyExportParams, PlyFlatSlices, PlyFormat, PlyGaussian, PlyReadStats, PlySceneData,
    PlySceneStats, PlyWriteStats,
};

/// Build a complete PLY header string for a 3DGS scene.
///
/// The header ends with `end_header\n`.
///
/// # Parameters
/// - `n_gaussians`: number of vertex elements.
/// - `sh_rest_count`: number of `f_rest_*` properties per Gaussian.
/// - `format`: the PLY format variant.
#[must_use]
pub fn ply_build_header(n_gaussians: usize, sh_rest_count: usize, format: PlyFormat) -> String {
    let mut h = String::with_capacity(2048);
    h.push_str("ply\n");
    h.push_str(&format!("format {} 1.0\n", format.as_ply_str()));
    h.push_str("comment Generated by OxiGAF (https://github.com/cool-japan/oxigaf)\n");
    h.push_str(&format!("element vertex {}\n", n_gaussians));
    for name in &["x", "y", "z"] {
        h.push_str(&format!("property float {}\n", name));
    }
    for name in &["nx", "ny", "nz"] {
        h.push_str(&format!("property float {}\n", name));
    }
    for i in 0..3 {
        h.push_str(&format!("property float f_dc_{}\n", i));
    }
    for i in 0..sh_rest_count {
        h.push_str(&format!("property float f_rest_{}\n", i));
    }
    h.push_str("property float opacity\n");
    for i in 0..3 {
        h.push_str(&format!("property float scale_{}\n", i));
    }
    for i in 0..4 {
        h.push_str(&format!("property float rot_{}\n", i));
    }
    h.push_str("end_header\n");
    h
}
/// Parse the element count for a named element from a PLY header string.
///
/// Example: for `"element vertex 1000"` with `element = "vertex"`, returns `1000`.
pub fn ply_parse_element_count(header: &str, element: &str) -> Result<usize, PlyError> {
    let prefix = format!("element {} ", element);
    for line in header.lines() {
        if line.starts_with(&prefix) {
            let rest = line.trim_start_matches(&prefix as &str).trim();
            return rest
                .parse::<usize>()
                .map_err(|_| PlyError::InvalidHeader(format!("cannot parse count in '{}'", line)));
        }
    }
    Err(PlyError::InvalidHeader(format!(
        "element '{}' not found in header",
        element
    )))
}
/// Parse the [`PlyFormat`] from the `format` line in a PLY header.
pub fn ply_parse_format(header: &str) -> Result<PlyFormat, PlyError> {
    for line in header.lines() {
        if line.starts_with("format ") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() < 2 {
                return Err(PlyError::InvalidHeader(format!(
                    "malformed format line: '{}'",
                    line
                )));
            }
            return match parts[1] {
                "ascii" => Ok(PlyFormat::Ascii),
                "binary_little_endian" => Ok(PlyFormat::BinaryLittleEndian),
                "binary_big_endian" => Ok(PlyFormat::BinaryBigEndian),
                other => Err(PlyError::UnsupportedFormat(other.to_owned())),
            };
        }
    }
    Err(PlyError::InvalidHeader("missing 'format' line".into()))
}
/// Extract the ordered list of vertex property names from a PLY header.
///
/// Only properties declared under `element vertex` are returned.
pub fn ply_parse_properties(header: &str) -> Result<Vec<String>, PlyError> {
    let mut in_vertex = false;
    let mut properties = Vec::new();
    for line in header.lines() {
        let line = line.trim();
        if line.starts_with("element vertex") {
            in_vertex = true;
        } else if line.starts_with("element ") {
            in_vertex = false;
        } else if in_vertex && line.starts_with("property ") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 3 {
                properties.push(parts[2].to_owned());
            }
        }
    }
    if properties.is_empty() {
        return Err(PlyError::InvalidHeader("no vertex properties found".into()));
    }
    Ok(properties)
}
/// Infer SH degree from a rest coefficient count.
///
/// `n_rest = (d+1)^2 * 3 - 3`  ⟹  `(d+1)^2 = (n_rest + 3) / 3`.
///
/// Returns an error if `n_rest` does not correspond to a valid degree.
fn sh_degree_from_n_rest(n_rest: usize) -> Result<usize, PlyError> {
    if n_rest == 0 {
        return Ok(0);
    }
    let total = n_rest + 3;
    if !total.is_multiple_of(3) {
        return Err(PlyError::InvalidData(format!(
            "n_rest={} is not divisible by 3",
            n_rest
        )));
    }
    let sq = total / 3;
    let d_plus_1 = (sq as f64).sqrt().round() as usize;
    if d_plus_1 * d_plus_1 != sq {
        return Err(PlyError::InvalidData(format!(
            "n_rest={} does not correspond to a valid SH degree",
            n_rest
        )));
    }
    Ok(d_plus_1 - 1)
}
/// Compute the total number of f32 properties per Gaussian given the SH rest count.
///
/// Layout: x y z nx ny nz + 3 dc + n_rest + opacity + 3 scale + 4 rot
#[inline]
fn n_properties_for_rest(n_rest: usize) -> usize {
    3 + 3 + 3 + n_rest + 1 + 3 + 4
}
/// Flatten a single [`PlyGaussian`] to a `Vec<f32>` in canonical property order.
fn gaussian_to_floats(g: &PlyGaussian) -> Vec<f32> {
    let mut v = Vec::with_capacity(n_properties_for_rest(g.f_rest.len()));
    v.push(g.x);
    v.push(g.y);
    v.push(g.z);
    v.push(g.nx);
    v.push(g.ny);
    v.push(g.nz);
    v.push(g.f_dc[0]);
    v.push(g.f_dc[1]);
    v.push(g.f_dc[2]);
    v.extend_from_slice(&g.f_rest);
    v.push(g.opacity);
    v.push(g.scale[0]);
    v.push(g.scale[1]);
    v.push(g.scale[2]);
    v.push(g.rot[0]);
    v.push(g.rot[1]);
    v.push(g.rot[2]);
    v.push(g.rot[3]);
    v
}
/// Parse a slice of f32 values (in property order) into a [`PlyGaussian`].
fn floats_to_gaussian(floats: &[f32], n_rest: usize) -> Result<PlyGaussian, PlyError> {
    let expected = n_properties_for_rest(n_rest);
    if floats.len() < expected {
        return Err(PlyError::DimensionMismatch {
            expected,
            got: floats.len(),
        });
    }
    let mut i = 0;
    let x = floats[i];
    i += 1;
    let y = floats[i];
    i += 1;
    let z = floats[i];
    i += 1;
    let nx = floats[i];
    i += 1;
    let ny = floats[i];
    i += 1;
    let nz = floats[i];
    i += 1;
    let f_dc = [floats[i], floats[i + 1], floats[i + 2]];
    i += 3;
    let f_rest = floats[i..i + n_rest].to_vec();
    i += n_rest;
    let opacity = floats[i];
    i += 1;
    let scale = [floats[i], floats[i + 1], floats[i + 2]];
    i += 3;
    let rot = [floats[i], floats[i + 1], floats[i + 2], floats[i + 3]];
    Ok(PlyGaussian {
        x,
        y,
        z,
        nx,
        ny,
        nz,
        f_dc,
        f_rest,
        opacity,
        scale,
        rot,
    })
}
/// Determine the rest coefficient count from a set of property names.
fn count_rest_from_properties(props: &[String]) -> usize {
    props.iter().filter(|p| p.starts_with("f_rest_")).count()
}
/// Write Gaussians to a PLY file using the ASCII format.
///
/// Uses `{:.9e}` notation to preserve f32 precision across the round-trip.
pub fn ply_write_ascii(path: &Path, gaussians: &[PlyGaussian]) -> Result<PlyWriteStats, PlyError> {
    if gaussians.is_empty() {
        return Err(PlyError::EmptyScene);
    }
    let n_rest = gaussians[0].f_rest.len();
    let n_props = n_properties_for_rest(n_rest);
    let sh_degree = sh_degree_from_n_rest(n_rest)?;
    let header = ply_build_header(gaussians.len(), n_rest, PlyFormat::Ascii);
    let file = std::fs::File::create(path)?;
    let mut writer = BufWriter::new(file);
    writer.write_all(header.as_bytes())?;
    for g in gaussians {
        let floats = gaussian_to_floats(g);
        let parts: Vec<String> = floats.iter().map(|v| format!("{:.9e}", v)).collect();
        writer.write_all(parts.join(" ").as_bytes())?;
        writer.write_all(b"\n")?;
    }
    writer.flush()?;
    drop(writer);
    let file_size_bytes = std::fs::metadata(path)?.len();
    Ok(PlyWriteStats {
        n_gaussians: gaussians.len(),
        n_properties: n_props,
        file_size_bytes,
        sh_degree,
        format: PlyFormat::Ascii,
    })
}
/// Write Gaussians to a PLY file using binary little-endian encoding.
pub fn ply_write_binary(path: &Path, gaussians: &[PlyGaussian]) -> Result<PlyWriteStats, PlyError> {
    if gaussians.is_empty() {
        return Err(PlyError::EmptyScene);
    }
    let n_rest = gaussians[0].f_rest.len();
    let n_props = n_properties_for_rest(n_rest);
    let sh_degree = sh_degree_from_n_rest(n_rest)?;
    let header = ply_build_header(gaussians.len(), n_rest, PlyFormat::BinaryLittleEndian);
    let file = std::fs::File::create(path)?;
    let mut writer = BufWriter::new(file);
    writer.write_all(header.as_bytes())?;
    for g in gaussians {
        let floats = gaussian_to_floats(g);
        for v in &floats {
            writer.write_all(&v.to_le_bytes())?;
        }
    }
    writer.flush()?;
    drop(writer);
    let file_size_bytes = std::fs::metadata(path)?.len();
    Ok(PlyWriteStats {
        n_gaussians: gaussians.len(),
        n_properties: n_props,
        file_size_bytes,
        sh_degree,
        format: PlyFormat::BinaryLittleEndian,
    })
}
/// Write Gaussians to a PLY file using the specified format.
///
/// `PlyFormat::BinaryBigEndian` is not supported for writing and returns
/// [`PlyError::UnsupportedFormat`].
pub fn ply_write(
    path: &Path,
    gaussians: &[PlyGaussian],
    format: PlyFormat,
) -> Result<PlyWriteStats, PlyError> {
    match format {
        PlyFormat::Ascii => ply_write_ascii(path, gaussians),
        PlyFormat::BinaryLittleEndian => ply_write_binary(path, gaussians),
        PlyFormat::BinaryBigEndian => Err(PlyError::UnsupportedFormat(
            "binary_big_endian write is not supported; use binary_little_endian".into(),
        )),
    }
}
/// Read a 3DGS PLY file, returning all Gaussians and summary statistics.
///
/// # Format support
///
/// - ASCII: each line after `end_header` is a space-separated row of floats.
/// - Binary little-endian: raw IEEE 754 f32 values packed sequentially.
/// - Binary big-endian: returns [`PlyError::UnsupportedFormat`].
pub fn ply_read(path: &Path) -> Result<(Vec<PlyGaussian>, PlyReadStats), PlyError> {
    let raw = std::fs::read(path)?;
    let end_marker = b"end_header\n";
    let header_end_pos = raw
        .windows(end_marker.len())
        .position(|w| w == end_marker)
        .ok_or_else(|| PlyError::InvalidHeader("missing 'end_header' line".into()))?;
    let header_bytes = &raw[..header_end_pos + end_marker.len()];
    let data_start = header_end_pos + end_marker.len();
    let header = std::str::from_utf8(header_bytes)
        .map_err(|_| PlyError::InvalidHeader("header is not valid UTF-8".into()))?;
    if !header.starts_with("ply\n") && !header.starts_with("ply\r\n") {
        return Err(PlyError::InvalidHeader(
            "file does not start with 'ply\\n'".into(),
        ));
    }
    let format = ply_parse_format(header)?;
    if format == PlyFormat::BinaryBigEndian {
        return Err(PlyError::UnsupportedFormat(
            "binary_big_endian read is not supported".into(),
        ));
    }
    let n_gaussians = ply_parse_element_count(header, "vertex")?;
    let props = ply_parse_properties(header)?;
    let n_rest = count_rest_from_properties(&props);
    let n_props = n_properties_for_rest(n_rest);
    let sh_degree = sh_degree_from_n_rest(n_rest)?;
    let gaussians = match format {
        PlyFormat::Ascii => {
            let data_slice = &raw[data_start..];
            let text = std::str::from_utf8(data_slice).map_err(|_| {
                PlyError::InvalidData("ASCII data section is not valid UTF-8".into())
            })?;
            let mut gaussians = Vec::with_capacity(n_gaussians);
            let mut line_no = 0usize;
            for line in text.lines() {
                if line_no >= n_gaussians {
                    break;
                }
                let line = line.trim();
                if line.is_empty() {
                    continue;
                }
                let floats: Vec<f32> = line
                    .split_whitespace()
                    .map(|tok| {
                        tok.parse::<f32>().map_err(|_| {
                            PlyError::InvalidData(format!(
                                "cannot parse float '{}' on data line {}",
                                tok,
                                line_no + 1
                            ))
                        })
                    })
                    .collect::<Result<_, _>>()?;
                if floats.len() < n_props {
                    return Err(PlyError::DimensionMismatch {
                        expected: n_props,
                        got: floats.len(),
                    });
                }
                gaussians.push(floats_to_gaussian(&floats, n_rest)?);
                line_no += 1;
            }
            if gaussians.len() != n_gaussians {
                return Err(PlyError::DimensionMismatch {
                    expected: n_gaussians,
                    got: gaussians.len(),
                });
            }
            gaussians
        }
        PlyFormat::BinaryLittleEndian => {
            let data = &raw[data_start..];
            let bytes_per_gaussian = n_props * 4;
            let expected_bytes = n_gaussians * bytes_per_gaussian;
            if data.len() < expected_bytes {
                return Err(PlyError::DimensionMismatch {
                    expected: expected_bytes,
                    got: data.len(),
                });
            }
            let mut gaussians = Vec::with_capacity(n_gaussians);
            for i in 0..n_gaussians {
                let offset = i * bytes_per_gaussian;
                let mut floats = Vec::with_capacity(n_props);
                for j in 0..n_props {
                    let byte_pos = offset + j * 4;
                    let bytes = [
                        data[byte_pos],
                        data[byte_pos + 1],
                        data[byte_pos + 2],
                        data[byte_pos + 3],
                    ];
                    floats.push(f32::from_le_bytes(bytes));
                }
                gaussians.push(floats_to_gaussian(&floats, n_rest)?);
            }
            gaussians
        }
        PlyFormat::BinaryBigEndian => unreachable!("filtered above"),
    };
    let stats = PlyReadStats {
        n_gaussians,
        n_properties: n_props,
        sh_degree,
        format,
    };
    Ok((gaussians, stats))
}
/// Export a complete 3DGS scene from flat training arrays to a PLY file.
///
/// # Array layout
///
/// | Field                     | Shape  | Description                      |
/// |---------------------------|--------|----------------------------------|
/// | `params.positions`        | N × 3  | World-space x, y, z              |
/// | `params.rotations`        | N × 4  | Quaternion qx, qy, qz, qw        |
/// | `params.scales`           | N × 3  | Log-space scales                 |
/// | `params.opacities`        | N      | Logit opacities                  |
/// | `params.sh_dc`            | N × 3  | SH DC coefficients               |
/// | `params.sh_rest`          | N × C  | SH rest coefficients             |
/// | `params.n_rest_per_gaussian` | scalar | C (0, 9, 24, or 45)           |
pub fn ply_export_scene(
    path: &Path,
    params: PlyExportParams<'_>,
) -> Result<PlyWriteStats, PlyError> {
    let PlyExportParams {
        positions,
        rotations,
        scales,
        opacities,
        sh_dc,
        sh_rest,
        n_rest_per_gaussian,
        format,
    } = params;
    let n = opacities.len();
    if n == 0 {
        return Err(PlyError::EmptyScene);
    }
    if positions.len() != n * 3 {
        return Err(PlyError::DimensionMismatch {
            expected: n * 3,
            got: positions.len(),
        });
    }
    if rotations.len() != n * 4 {
        return Err(PlyError::DimensionMismatch {
            expected: n * 4,
            got: rotations.len(),
        });
    }
    if scales.len() != n * 3 {
        return Err(PlyError::DimensionMismatch {
            expected: n * 3,
            got: scales.len(),
        });
    }
    if sh_dc.len() != n * 3 {
        return Err(PlyError::DimensionMismatch {
            expected: n * 3,
            got: sh_dc.len(),
        });
    }
    if n_rest_per_gaussian > 0 && sh_rest.len() != n * n_rest_per_gaussian {
        return Err(PlyError::DimensionMismatch {
            expected: n * n_rest_per_gaussian,
            got: sh_rest.len(),
        });
    }
    let mut gaussians = Vec::with_capacity(n);
    for i in 0..n {
        let g = PlyGaussian::from_flat(
            PlyFlatSlices {
                positions,
                rotations,
                scales,
                opacities,
                sh_dc,
                sh_rest,
                n_rest: n_rest_per_gaussian,
            },
            i,
        )?;
        gaussians.push(g);
    }
    ply_write(path, &gaussians, format)
}
/// Import a PLY file back into flat training arrays.
///
/// Rotation output is `(qx, qy, qz, qw)` — the inverse of the PLY's `(w,x,y,z)` storage.
pub fn ply_import_scene(path: &Path) -> Result<PlySceneData, PlyError> {
    let (gaussians, _stats) = ply_read(path)?;
    let n = gaussians.len();
    let n_rest = gaussians.first().map_or(0, |g| g.f_rest.len());
    let mut positions = Vec::with_capacity(n * 3);
    let mut rotations = Vec::with_capacity(n * 4);
    let mut scales = Vec::with_capacity(n * 3);
    let mut opacities = Vec::with_capacity(n);
    let mut sh_dc = Vec::with_capacity(n * 3);
    let mut sh_rest = Vec::with_capacity(n * n_rest.max(1));
    for g in &gaussians {
        positions.push(g.x);
        positions.push(g.y);
        positions.push(g.z);
        rotations.push(g.rot[1]);
        rotations.push(g.rot[2]);
        rotations.push(g.rot[3]);
        rotations.push(g.rot[0]);
        scales.push(g.scale[0]);
        scales.push(g.scale[1]);
        scales.push(g.scale[2]);
        opacities.push(g.opacity);
        sh_dc.push(g.f_dc[0]);
        sh_dc.push(g.f_dc[1]);
        sh_dc.push(g.f_dc[2]);
        sh_rest.extend_from_slice(&g.f_rest);
    }
    Ok(PlySceneData {
        positions,
        rotations,
        scales,
        opacities,
        sh_dc,
        sh_rest,
        n_gaussians: n,
        n_rest_per_gaussian: n_rest,
    })
}
/// Compute scene statistics for a slice of Gaussians.
///
/// Returns zeroed stats for an empty slice.
#[must_use]
pub fn ply_compute_scene_stats(gaussians: &[PlyGaussian]) -> PlySceneStats {
    if gaussians.is_empty() {
        return PlySceneStats {
            n_gaussians: 0,
            sh_degree: 0,
            mean_opacity: 0.0,
            mean_scale: 0.0,
            bbox_min: [0.0; 3],
            bbox_max: [0.0; 3],
        };
    }
    let n_rest = gaussians[0].f_rest.len();
    let sh_degree = sh_degree_from_n_rest(n_rest).unwrap_or(0);
    let mut sum_opacity = 0.0f64;
    let mut sum_scale = 0.0f64;
    let mut bbox_min = [f32::INFINITY; 3];
    let mut bbox_max = [f32::NEG_INFINITY; 3];
    for g in gaussians {
        sum_opacity += g.real_opacity() as f64;
        let rs = g.real_scale();
        let scale_mean = (rs[0] + rs[1] + rs[2]) / 3.0;
        sum_scale += scale_mean as f64;
        let pos = [g.x, g.y, g.z];
        for k in 0..3 {
            if pos[k] < bbox_min[k] {
                bbox_min[k] = pos[k];
            }
            if pos[k] > bbox_max[k] {
                bbox_max[k] = pos[k];
            }
        }
    }
    let n = gaussians.len() as f64;
    PlySceneStats {
        n_gaussians: gaussians.len(),
        sh_degree,
        mean_opacity: (sum_opacity / n) as f32,
        mean_scale: (sum_scale / n) as f32,
        bbox_min,
        bbox_max,
    }
}
/// Format scene statistics as a human-readable string.
#[must_use]
pub fn ply_format_stats(stats: &PlySceneStats) -> String {
    format!(
        "Gaussians: {}\n\
         SH degree: {}\n\
         Mean opacity: {:.4}\n\
         Mean scale:   {:.6}\n\
         BBox min: ({:.4}, {:.4}, {:.4})\n\
         BBox max: ({:.4}, {:.4}, {:.4})",
        stats.n_gaussians,
        stats.sh_degree,
        stats.mean_opacity,
        stats.mean_scale,
        stats.bbox_min[0],
        stats.bbox_min[1],
        stats.bbox_min[2],
        stats.bbox_max[0],
        stats.bbox_max[1],
        stats.bbox_max[2],
    )
}
/// Format write statistics as a human-readable string.
#[must_use]
pub fn ply_format_write_stats(stats: &PlyWriteStats) -> String {
    format!(
        "Written {} Gaussians ({} properties each, SH degree {})\n\
         Format: {:?}\n\
         File size: {} bytes",
        stats.n_gaussians, stats.n_properties, stats.sh_degree, stats.format, stats.file_size_bytes,
    )
}
