//! Export utilities — PLY file I/O, model loading, and point-cloud rendering.
//!
//! The PLY writer produces standard 3D Gaussian Splatting ASCII PLY files that
//! are compatible with viewers like `splatfacto` and the original 3DGS codebase.
//!
//! Supported formats:
//! * PLY — Standard 3D Gaussian Splatting format
//! * safetensors — Efficient tensor storage
//! * glTF 2.0 — Standard 3D format with custom Gaussian extension
//! * JSON — Checkpoint format for resuming training

use std::collections::HashMap;
use std::io::{BufWriter, Write};
use std::path::Path;

use anyhow::{Context, Result};
use image::{Rgb, RgbImage};
use nalgebra as na;
use serde::{Deserialize, Serialize};

use oxigaf::flame::Camera;
use oxigaf::render::gaussian::{GaussianAttributes, GaussianModel};
use oxigaf::trainer::checkpoint;
use safetensors::tensor::{Dtype, TensorView};

// ---------------------------------------------------------------------------
// PLY export
// ---------------------------------------------------------------------------

/// Write a [`GaussianModel`] to an ASCII PLY file.
///
/// The file follows the standard 3D Gaussian Splatting format:
///
/// | Property group | Fields |
/// |----------------|--------|
/// | Position       | `x y z` |
/// | Normal         | `nx ny nz` (zeros — for compatibility) |
/// | SH DC          | `f_dc_0 f_dc_1 f_dc_2` |
/// | SH rest        | `f_rest_0 … f_rest_N` |
/// | Opacity        | `opacity` (pre-sigmoid) |
/// | Scale          | `scale_0 scale_1 scale_2` (log-scale) |
/// | Rotation       | `rot_0 rot_1 rot_2 rot_3` (w, x, y, z) |
pub fn export_ply(model: &GaussianModel, path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }

    let file = std::fs::File::create(path)
        .with_context(|| format!("Failed to create PLY file: {}", path.display()))?;
    let mut w = BufWriter::new(file);

    let n = model.len();
    let sh_channels = ((model.sh_degree + 1).pow(2) * 3) as usize;
    let sh_rest = sh_channels.saturating_sub(3);

    // ----- Header -----
    writeln!(w, "ply")?;
    writeln!(w, "format ascii 1.0")?;
    writeln!(w, "comment Generated by OxiGAF")?;
    writeln!(w, "comment SH degree {}", model.sh_degree)?;
    writeln!(w, "element vertex {n}")?;
    // Position
    writeln!(w, "property float x")?;
    writeln!(w, "property float y")?;
    writeln!(w, "property float z")?;
    // Normal (compatibility — always zero)
    writeln!(w, "property float nx")?;
    writeln!(w, "property float ny")?;
    writeln!(w, "property float nz")?;
    // SH DC
    for c in 0..3 {
        writeln!(w, "property float f_dc_{c}")?;
    }
    // SH higher-order
    for i in 0..sh_rest {
        writeln!(w, "property float f_rest_{i}")?;
    }
    // Opacity, scale, rotation
    writeln!(w, "property float opacity")?;
    writeln!(w, "property float scale_0")?;
    writeln!(w, "property float scale_1")?;
    writeln!(w, "property float scale_2")?;
    writeln!(w, "property float rot_0")?;
    writeln!(w, "property float rot_1")?;
    writeln!(w, "property float rot_2")?;
    writeln!(w, "property float rot_3")?;
    writeln!(w, "end_header")?;

    // ----- Vertex data -----
    for i in 0..n {
        let g = &model.gaussians[i];
        let sh_base = i * sh_channels;

        // Position
        write!(w, "{} {} {}", g.position[0], g.position[1], g.position[2])?;
        // Normal
        write!(w, " 0 0 0")?;
        // SH DC
        for c in 0..3 {
            let v = model.sh_coeffs.get(sh_base + c).copied().unwrap_or(0.0);
            write!(w, " {v}")?;
        }
        // SH rest
        for c in 3..sh_channels {
            let v = model.sh_coeffs.get(sh_base + c).copied().unwrap_or(0.0);
            write!(w, " {v}")?;
        }
        // Opacity (pre-sigmoid)
        write!(w, " {}", g.opacity)?;
        // Scale (log-scale)
        write!(w, " {} {} {}", g.scale[0], g.scale[1], g.scale[2])?;
        // Rotation: convert from internal (x,y,z,w) → PLY (w,x,y,z)
        writeln!(
            w,
            " {} {} {} {}",
            g.rotation[3], g.rotation[0], g.rotation[1], g.rotation[2]
        )?;
    }

    w.flush()?;
    tracing::info!(
        "Wrote {} Gaussians (SH degree {}) to {}",
        n,
        model.sh_degree,
        path.display(),
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Safetensors export
// ---------------------------------------------------------------------------

/// Write a [`GaussianModel`] to a safetensors file.
///
/// Tensors saved:
/// * `positions` — `[N, 3]` f32
/// * `rotations` — `[N, 4]` f32
/// * `scales`    — `[N, 3]` f32
/// * `opacities` — `[N]` f32
/// * `sh_coeffs` — `[N, C]` f32 where `C = (degree+1)² × 3`
///
/// Metadata includes `sh_degree`.
pub fn export_safetensors(model: &GaussianModel, path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }

    let n = model.len();
    let sh_channels = ((model.sh_degree + 1).pow(2) * 3) as usize;

    // Extract dense f32 arrays from GaussianAttributes.
    let positions: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.position.iter().copied())
        .collect();
    let rotations: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.rotation.iter().copied())
        .collect();
    let scales: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.scale.iter().copied())
        .collect();
    let opacities: Vec<f32> = model.gaussians.iter().map(|g| g.opacity).collect();

    // Pad or truncate SH coefficients.
    let mut sh_data = model.sh_coeffs.clone();
    sh_data.resize(n * sh_channels, 0.0);

    // Build tensor views.
    let pos_view = TensorView::new(Dtype::F32, vec![n, 3], bytemuck::cast_slice(&positions))?;
    let rot_view = TensorView::new(Dtype::F32, vec![n, 4], bytemuck::cast_slice(&rotations))?;
    let scl_view = TensorView::new(Dtype::F32, vec![n, 3], bytemuck::cast_slice(&scales))?;
    let opa_view = TensorView::new(Dtype::F32, vec![n], bytemuck::cast_slice(&opacities))?;
    let sh_view = TensorView::new(
        Dtype::F32,
        vec![n, sh_channels],
        bytemuck::cast_slice(&sh_data),
    )?;

    let tensors: Vec<(&str, TensorView<'_>)> = vec![
        ("positions", pos_view),
        ("rotations", rot_view),
        ("scales", scl_view),
        ("opacities", opa_view),
        ("sh_coeffs", sh_view),
    ];

    // Metadata.
    let mut metadata = HashMap::new();
    metadata.insert("sh_degree".to_string(), model.sh_degree.to_string());
    metadata.insert("num_gaussians".to_string(), n.to_string());

    // Serialize to bytes, then write to file.
    let data = safetensors::serialize(tensors, Some(metadata))
        .map_err(|e| anyhow::anyhow!("Failed to serialize safetensors: {e}"))?;

    std::fs::write(path, &data)
        .with_context(|| format!("Failed to write safetensors file: {}", path.display()))?;

    tracing::info!(
        "Wrote {} Gaussians (SH degree {}) to {}",
        n,
        model.sh_degree,
        path.display(),
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// PLY import
// ---------------------------------------------------------------------------

/// Load a [`GaussianModel`] from an ASCII PLY file.
///
/// The property names in the header are used to map columns to fields, so PLY
/// files produced by other 3DGS implementations should be loadable.
pub fn load_ply(path: &Path) -> Result<GaussianModel> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to read PLY file: {}", path.display()))?;
    let mut lines = content.lines();

    // ----- Parse header -----
    let mut num_vertices: usize = 0;
    let mut properties: Vec<String> = Vec::new();

    for line in lines.by_ref() {
        let line = line.trim();
        if line == "end_header" {
            break;
        }
        if let Some(rest) = line.strip_prefix("element vertex ") {
            num_vertices = rest
                .trim()
                .parse()
                .context("Invalid vertex count in PLY header")?;
        }
        if line.starts_with("property float") {
            if let Some(name) = line.split_whitespace().last() {
                properties.push(name.to_string());
            }
        }
    }

    anyhow::ensure!(num_vertices > 0, "PLY file has no vertices");
    anyhow::ensure!(!properties.is_empty(), "PLY file has no float properties");

    // Build property → column-index map
    let prop_map: HashMap<&str, usize> = properties
        .iter()
        .enumerate()
        .map(|(i, p)| (p.as_str(), i))
        .collect();

    let idx = |name: &str| -> Option<usize> { prop_map.get(name).copied() };

    // Determine SH degree from property names
    let num_sh_rest = properties
        .iter()
        .filter(|p| p.starts_with("f_rest_"))
        .count();
    let total_sh = 3 + num_sh_rest; // DC(3) + rest
    let bands_sq = total_sh / 3;
    let sh_degree = ((bands_sq as f32).sqrt() as u32).saturating_sub(1);
    let sh_channels = ((sh_degree + 1).pow(2) * 3) as usize;

    // ----- Parse vertex data -----
    let mut gaussians = Vec::with_capacity(num_vertices);
    let mut sh_coeffs = Vec::with_capacity(num_vertices * sh_channels);

    for line_num in 0..num_vertices {
        let line = lines.next().with_context(|| {
            format!(
                "Unexpected end of PLY data at vertex {}/{}",
                line_num, num_vertices
            )
        })?;
        let values: Vec<f32> = line
            .split_whitespace()
            .map(|v| v.parse::<f32>().unwrap_or(0.0))
            .collect();

        let get = |name: &str, default: f32| -> f32 {
            idx(name)
                .and_then(|i| values.get(i).copied())
                .unwrap_or(default)
        };

        let x = get("x", 0.0);
        let y = get("y", 0.0);
        let z = get("z", 0.0);
        let opacity = get("opacity", 0.0);
        let scale_0 = get("scale_0", -5.0);
        let scale_1 = get("scale_1", -5.0);
        let scale_2 = get("scale_2", -5.0);

        // PLY: (w,x,y,z) → internal: (x,y,z,w)
        let rot_w = get("rot_0", 1.0);
        let rot_x = get("rot_1", 0.0);
        let rot_y = get("rot_2", 0.0);
        let rot_z = get("rot_3", 0.0);

        gaussians.push(GaussianAttributes {
            position: [x, y, z],
            _pad0: 0.0,
            rotation: [rot_x, rot_y, rot_z, rot_w],
            scale: [scale_0, scale_1, scale_2],
            opacity,
        });

        // SH coefficients (DC then rest)
        for c in 0..3 {
            let name = format!("f_dc_{c}");
            sh_coeffs.push(get(&name, 0.0));
        }
        for r in 0..num_sh_rest {
            let name = format!("f_rest_{r}");
            sh_coeffs.push(get(&name, 0.0));
        }
        // Pad to expected sh_channels if file has fewer SH than the degree implies
        let written = 3 + num_sh_rest;
        if written < sh_channels {
            sh_coeffs.extend(std::iter::repeat_n(0.0, sh_channels - written));
        }
    }

    tracing::info!(
        "Loaded {} Gaussians (SH degree {}) from {}",
        gaussians.len(),
        sh_degree,
        path.display(),
    );

    Ok(GaussianModel {
        gaussians,
        sh_coeffs,
        sh_degree,
        // FLAME binding info is not stored in PLY — use placeholders.
        face_indices: vec![0; num_vertices],
        barycentric: vec![[1.0 / 3.0; 3]; num_vertices],
        local_offsets: vec![[0.0; 3]; num_vertices],
        is_rigid: vec![true; num_vertices],
    })
}

// ---------------------------------------------------------------------------
// Model loading (checkpoint JSON or PLY)
// ---------------------------------------------------------------------------

/// Load a [`GaussianModel`] from either a checkpoint JSON file or a PLY file.
///
/// The format is determined by the file extension:
/// * `.json` — OxiGAF checkpoint (includes optimizer state, iteration, etc.)
/// * `.ply`  — Standard 3DGS PLY (position, SH, opacity, scale, rotation)
pub fn load_model(path: &Path) -> Result<GaussianModel> {
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_lowercase();

    match ext.as_str() {
        "json" => {
            tracing::info!("Loading model from checkpoint: {}", path.display());
            let data = checkpoint::load_checkpoint(path)
                .with_context(|| format!("Failed to load checkpoint: {}", path.display()))?;
            let model = checkpoint::restore_model(&data);
            tracing::info!(
                "Restored model: {} Gaussians (iteration {})",
                model.len(),
                data.iteration,
            );
            Ok(model)
        }
        "ply" => {
            tracing::info!("Loading model from PLY: {}", path.display());
            load_ply(path)
        }
        other => {
            anyhow::bail!(
                "Unsupported model format '{}'. Expected .json (checkpoint) or .ply",
                other,
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Point-cloud software renderer
// ---------------------------------------------------------------------------

/// SH band-0 normalisation constant: `0.5 / Y₀⁰` where `Y₀⁰ = 0.5·√(1/π)`.
const SH_C0: f32 = 0.282_094_8;

/// Render a simple point-cloud visualisation of a [`GaussianModel`].
///
/// Each Gaussian is splatted as a small filled circle at its projected pixel
/// position, coloured by its SH DC coefficient.  A Z-buffer ensures correct
/// depth ordering.  This is intentionally a lightweight software renderer for
/// quick previews — the full GPU rasteriser is in `oxigaf-render`.
pub fn render_point_cloud(model: &GaussianModel, camera: &Camera) -> RgbImage {
    let w = camera.width as usize;
    let h = camera.height as usize;
    let mut img = RgbImage::from_pixel(camera.width, camera.height, Rgb([30, 30, 30]));
    let mut depth_buf = vec![f32::INFINITY; w * h];

    let sh_channels = ((model.sh_degree + 1).pow(2) * 3) as usize;
    let splat_radius: i32 = 2;
    let r2 = splat_radius * splat_radius;

    for (i, g) in model.gaussians.iter().enumerate() {
        // Skip nearly-transparent Gaussians (sigmoid(opacity) < 0.01)
        if g.opacity < -4.6 {
            continue;
        }

        let p = na::Point3::new(g.position[0], g.position[1], g.position[2]);
        let p_cam = camera.world_to_cam(&p);

        if p_cam.z <= camera.near || p_cam.z >= camera.far {
            continue;
        }

        let [px, py] = camera.project(&p_cam);
        let cx = px.round() as i32;
        let cy = py.round() as i32;

        // SH DC → colour
        let sh_base = i * sh_channels;
        let r_f =
            (model.sh_coeffs.get(sh_base).copied().unwrap_or(0.0) * SH_C0 + 0.5).clamp(0.0, 1.0);
        let g_f = (model.sh_coeffs.get(sh_base + 1).copied().unwrap_or(0.0) * SH_C0 + 0.5)
            .clamp(0.0, 1.0);
        let b_f = (model.sh_coeffs.get(sh_base + 2).copied().unwrap_or(0.0) * SH_C0 + 0.5)
            .clamp(0.0, 1.0);

        let color = Rgb([
            (r_f * 255.0) as u8,
            (g_f * 255.0) as u8,
            (b_f * 255.0) as u8,
        ]);

        // Draw a small filled circle at the projected position.
        for dy in -splat_radius..=splat_radius {
            for dx in -splat_radius..=splat_radius {
                if dx * dx + dy * dy > r2 {
                    continue;
                }
                let ix = cx + dx;
                let iy = cy + dy;
                if ix < 0 || ix >= w as i32 || iy < 0 || iy >= h as i32 {
                    continue;
                }
                let pidx = iy as usize * w + ix as usize;
                if p_cam.z < depth_buf[pidx] {
                    depth_buf[pidx] = p_cam.z;
                    img.put_pixel(ix as u32, iy as u32, color);
                }
            }
        }
    }

    img
}

// ---------------------------------------------------------------------------
// glTF 2.0 export
// ---------------------------------------------------------------------------

/// glTF 2.0 asset with Gaussian extension.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GltfAsset {
    version: String,
    generator: String,
}

/// glTF buffer view.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GltfBufferView {
    buffer: usize,
    byte_offset: usize,
    byte_length: usize,
    byte_stride: Option<usize>,
}

/// glTF accessor.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GltfAccessor {
    buffer_view: usize,
    component_type: u32,
    count: usize,
    #[serde(rename = "type")]
    accessor_type: String,
    min: Option<Vec<f32>>,
    max: Option<Vec<f32>>,
}

/// glTF node.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GltfNode {
    name: String,
    mesh: Option<usize>,
    extensions: Option<HashMap<String, serde_json::Value>>,
}

/// glTF mesh.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GltfMesh {
    name: String,
    primitives: Vec<GltfPrimitive>,
}

/// glTF primitive.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GltfPrimitive {
    attributes: HashMap<String, usize>,
    mode: u32,
}

/// glTF scene.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GltfScene {
    name: String,
    nodes: Vec<usize>,
}

/// Full glTF document.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GltfDocument {
    asset: GltfAsset,
    scene: usize,
    scenes: Vec<GltfScene>,
    nodes: Vec<GltfNode>,
    meshes: Vec<GltfMesh>,
    accessors: Vec<GltfAccessor>,
    buffer_views: Vec<GltfBufferView>,
    buffers: Vec<GltfBuffer>,
    extensions_used: Vec<String>,
    extensions: Option<HashMap<String, serde_json::Value>>,
}

/// glTF buffer.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GltfBuffer {
    byte_length: usize,
    uri: Option<String>,
}

/// Gaussian extension data.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GaussianExtension {
    sh_degree: u32,
    num_gaussians: usize,
    rotations_accessor: usize,
    scales_accessor: usize,
    opacities_accessor: usize,
    sh_coeffs_accessor: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    metadata: Option<GaussianMetadata>,
}

/// Training metadata for glTF export.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct GaussianMetadata {
    version: String,
    generator: String,
    export_time: String,
    model_stats: ModelStats,
}

/// Model statistics.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct ModelStats {
    num_gaussians: usize,
    sh_degree: u32,
    rigid_count: usize,
    flexible_count: usize,
}

/// Export a [`GaussianModel`] to glTF 2.0 format with custom Gaussian extension.
///
/// The output is a GLB (binary glTF) file that embeds all data.
/// A custom extension `OXIGAF_gaussians` stores Gaussian-specific attributes.
///
/// If `include_metadata` is true, training metadata is included in the extension.
pub fn export_gltf(model: &GaussianModel, path: &Path, include_metadata: bool) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }

    let n = model.len();
    let sh_channels = ((model.sh_degree + 1).pow(2) * 3) as usize;

    // Build binary buffer with all data
    let mut buffer_data = Vec::new();
    let mut buffer_views = Vec::new();
    let mut accessors = Vec::new();

    // Helper to add a buffer view and accessor
    let mut add_accessor =
        |data: &[f32], count: usize, components: usize, accessor_type: &str| -> usize {
            let byte_offset = buffer_data.len();
            let byte_length = data.len() * 4;

            buffer_data.extend(bytemuck::cast_slice::<f32, u8>(data));

            let view_idx = buffer_views.len();
            buffer_views.push(GltfBufferView {
                buffer: 0,
                byte_offset,
                byte_length,
                byte_stride: if components > 1 {
                    Some(components * 4)
                } else {
                    None
                },
            });

            let accessor_idx = accessors.len();
            accessors.push(GltfAccessor {
                buffer_view: view_idx,
                component_type: 5126, // FLOAT
                count,
                accessor_type: accessor_type.to_string(),
                min: None,
                max: None,
            });

            accessor_idx
        };

    // Positions (required for point cloud visualization)
    let positions: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.position.iter().copied())
        .collect();
    let pos_accessor = add_accessor(&positions, n, 3, "VEC3");

    // Rotations (quaternion xyzw)
    let rotations: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.rotation.iter().copied())
        .collect();
    let rot_accessor = add_accessor(&rotations, n, 4, "VEC4");

    // Scales (log-scale)
    let scales: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.scale.iter().copied())
        .collect();
    let scale_accessor = add_accessor(&scales, n, 3, "VEC3");

    // Opacities (pre-sigmoid)
    let opacities: Vec<f32> = model.gaussians.iter().map(|g| g.opacity).collect();
    let opacity_accessor = add_accessor(&opacities, n, 1, "SCALAR");

    // SH coefficients
    let mut sh_data = model.sh_coeffs.clone();
    sh_data.resize(n * sh_channels, 0.0);
    let sh_accessor = add_accessor(&sh_data, n * sh_channels, 1, "SCALAR");

    // Build glTF document
    let metadata = if include_metadata {
        let rigid_count = model.is_rigid.iter().filter(|&&r| r).count();
        let flexible_count = model.is_rigid.iter().filter(|&&r| !r).count();
        Some(GaussianMetadata {
            version: env!("CARGO_PKG_VERSION").to_string(),
            generator: format!("OxiGAF v{}", env!("CARGO_PKG_VERSION")),
            export_time: chrono::Utc::now().to_rfc3339(),
            model_stats: ModelStats {
                num_gaussians: n,
                sh_degree: model.sh_degree,
                rigid_count,
                flexible_count,
            },
        })
    } else {
        None
    };

    let gaussian_ext = GaussianExtension {
        sh_degree: model.sh_degree,
        num_gaussians: n,
        rotations_accessor: rot_accessor,
        scales_accessor: scale_accessor,
        opacities_accessor: opacity_accessor,
        sh_coeffs_accessor: sh_accessor,
        metadata,
    };

    let mut node_extensions = HashMap::new();
    node_extensions.insert(
        "OXIGAF_gaussians".to_string(),
        serde_json::to_value(&gaussian_ext).unwrap_or_default(),
    );

    let document = GltfDocument {
        asset: GltfAsset {
            version: "2.0".to_string(),
            generator: format!("OxiGAF v{}", env!("CARGO_PKG_VERSION")),
        },
        scene: 0,
        scenes: vec![GltfScene {
            name: "GaussianScene".to_string(),
            nodes: vec![0],
        }],
        nodes: vec![GltfNode {
            name: "GaussianCloud".to_string(),
            mesh: Some(0),
            extensions: Some(node_extensions),
        }],
        meshes: vec![GltfMesh {
            name: "GaussianMesh".to_string(),
            primitives: vec![GltfPrimitive {
                attributes: {
                    let mut attrs = HashMap::new();
                    attrs.insert("POSITION".to_string(), pos_accessor);
                    attrs
                },
                mode: 0, // POINTS
            }],
        }],
        accessors,
        buffer_views,
        buffers: vec![GltfBuffer {
            byte_length: buffer_data.len(),
            uri: None, // Embedded in GLB
        }],
        extensions_used: vec!["OXIGAF_gaussians".to_string()],
        extensions: None,
    };

    // Write GLB file
    let json_str = serde_json::to_string(&document).context("Failed to serialize glTF document")?;

    // Pad JSON to 4-byte boundary
    let json_bytes = json_str.as_bytes();
    let json_padding = (4 - (json_bytes.len() % 4)) % 4;
    let json_chunk_length = json_bytes.len() + json_padding;

    // Pad buffer to 4-byte boundary
    let bin_padding = (4 - (buffer_data.len() % 4)) % 4;
    let bin_chunk_length = buffer_data.len() + bin_padding;

    // GLB header + chunks
    let total_length = 12 + 8 + json_chunk_length + 8 + bin_chunk_length;

    let file = std::fs::File::create(path)
        .with_context(|| format!("Failed to create glTF file: {}", path.display()))?;
    let mut w = BufWriter::new(file);

    // GLB header
    w.write_all(b"glTF")?; // Magic
    w.write_all(&2u32.to_le_bytes())?; // Version
    w.write_all(&(total_length as u32).to_le_bytes())?; // Total length

    // JSON chunk
    w.write_all(&(json_chunk_length as u32).to_le_bytes())?;
    w.write_all(&0x4E4F534Au32.to_le_bytes())?; // "JSON"
    w.write_all(json_bytes)?;
    for _ in 0..json_padding {
        w.write_all(b" ")?;
    }

    // Binary chunk
    w.write_all(&(bin_chunk_length as u32).to_le_bytes())?;
    w.write_all(&0x004E4942u32.to_le_bytes())?; // "BIN\0"
    w.write_all(&buffer_data)?;
    for _ in 0..bin_padding {
        w.write_all(&[0u8])?;
    }

    w.flush()?;

    tracing::info!(
        "Wrote {} Gaussians (SH degree {}) to glTF: {}",
        n,
        model.sh_degree,
        path.display(),
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// JSON checkpoint export
// ---------------------------------------------------------------------------

/// JSON checkpoint data structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JsonCheckpoint {
    /// Checkpoint format version.
    pub version: String,
    /// Training iteration (0 for exported models).
    pub iteration: u32,
    /// Number of Gaussians.
    pub num_gaussians: usize,
    /// SH degree.
    pub sh_degree: u32,
    /// Gaussian positions (flattened [x, y, z, ...]).
    pub positions: Vec<f32>,
    /// Gaussian rotations (flattened [x, y, z, w, ...]).
    pub rotations: Vec<f32>,
    /// Gaussian scales (flattened [sx, sy, sz, ...]).
    pub scales: Vec<f32>,
    /// Gaussian opacities.
    pub opacities: Vec<f32>,
    /// SH coefficients (flattened).
    pub sh_coeffs: Vec<f32>,
    /// FLAME binding: face indices.
    pub face_indices: Vec<u32>,
    /// FLAME binding: barycentric coordinates.
    pub barycentric: Vec<[f32; 3]>,
    /// FLAME binding: local offsets.
    pub local_offsets: Vec<[f32; 3]>,
    /// Whether each Gaussian is rigid.
    pub is_rigid: Vec<bool>,
    /// Metadata.
    pub metadata: HashMap<String, String>,
}

/// Export a [`GaussianModel`] to JSON checkpoint format.
///
/// This format includes all Gaussian attributes and FLAME binding information,
/// making it suitable for resuming training or transferring models.
pub fn export_json_checkpoint(model: &GaussianModel, path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }

    let n = model.len();

    // Extract data from model
    let positions: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.position.iter().copied())
        .collect();
    let rotations: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.rotation.iter().copied())
        .collect();
    let scales: Vec<f32> = model
        .gaussians
        .iter()
        .flat_map(|g| g.scale.iter().copied())
        .collect();
    let opacities: Vec<f32> = model.gaussians.iter().map(|g| g.opacity).collect();

    let mut metadata = HashMap::new();
    metadata.insert(
        "generator".to_string(),
        format!("OxiGAF v{}", env!("CARGO_PKG_VERSION")),
    );
    metadata.insert("export_time".to_string(), chrono::Utc::now().to_rfc3339());

    let checkpoint = JsonCheckpoint {
        version: "1.0".to_string(),
        iteration: 0, // Export, not from training
        num_gaussians: n,
        sh_degree: model.sh_degree,
        positions,
        rotations,
        scales,
        opacities,
        sh_coeffs: model.sh_coeffs.clone(),
        face_indices: model.face_indices.clone(),
        barycentric: model.barycentric.clone(),
        local_offsets: model.local_offsets.clone(),
        is_rigid: model.is_rigid.clone(),
        metadata,
    };

    let json_str =
        serde_json::to_string_pretty(&checkpoint).context("Failed to serialize checkpoint")?;

    std::fs::write(path, json_str)
        .with_context(|| format!("Failed to write checkpoint: {}", path.display()))?;

    tracing::info!(
        "Wrote {} Gaussians (SH degree {}) to JSON checkpoint: {}",
        n,
        model.sh_degree,
        path.display(),
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Multi-Progress Example for Parallel Exports
// ---------------------------------------------------------------------------

/// Export a model to multiple formats in parallel with progress tracking.
///
/// This function demonstrates using `multi_progress` for parallel export operations.
/// Each format export gets its own progress bar that updates independently.
///
/// # Example
///
/// ```no_run
/// use oxigaf_cli::export::export_all_formats_parallel;
/// use oxigaf::render::gaussian::GaussianModel;
/// use oxigaf_cli::verbosity::Verbosity;
/// use std::path::Path;
///
/// # fn example(model: GaussianModel) -> anyhow::Result<()> {
/// let output_dir = Path::new("output");
/// export_all_formats_parallel(&model, output_dir, Verbosity::Normal)?;
/// # Ok(())
/// # }
/// ```
#[allow(dead_code)]
pub fn export_all_formats_parallel(
    model: &GaussianModel,
    output_dir: &Path,
    verbosity: crate::verbosity::Verbosity,
) -> Result<()> {
    use crate::progress;
    use std::thread;

    std::fs::create_dir_all(output_dir).with_context(|| {
        format!(
            "Failed to create output directory: {}",
            output_dir.display()
        )
    })?;

    // Check if we should show progress
    if let Some(multi) = progress::multi_progress(verbosity) {
        // Create progress bars for each format
        let pb_ply = multi.add(progress::export_progress(1, verbosity));
        pb_ply.set_message("PLY");

        let pb_safetensors = multi.add(progress::export_progress(1, verbosity));
        pb_safetensors.set_message("safetensors");

        let pb_gltf = multi.add(progress::export_progress(1, verbosity));
        pb_gltf.set_message("glTF");

        let pb_json = multi.add(progress::export_progress(1, verbosity));
        pb_json.set_message("JSON");

        // Clone model data for parallel exports
        let model_ply = model.clone();
        let model_safetensors = model.clone();
        let model_gltf = model.clone();
        let model_json = model.clone();

        let ply_path = output_dir.join("model.ply");
        let safetensors_path = output_dir.join("model.safetensors");
        let gltf_path = output_dir.join("model.gltf");
        let json_path = output_dir.join("model.json");

        // Spawn parallel export threads
        let handle_ply = thread::spawn(move || {
            let result = export_ply(&model_ply, &ply_path);
            pb_ply.inc(1);
            pb_ply.finish_with_message("✓ PLY");
            result
        });

        let handle_safetensors = thread::spawn(move || {
            let result = export_safetensors(&model_safetensors, &safetensors_path);
            pb_safetensors.inc(1);
            pb_safetensors.finish_with_message("✓ safetensors");
            result
        });

        let handle_gltf = thread::spawn(move || {
            let result = export_gltf(&model_gltf, &gltf_path, true);
            pb_gltf.inc(1);
            pb_gltf.finish_with_message("✓ glTF");
            result
        });

        let handle_json = thread::spawn(move || {
            let result = export_json_checkpoint(&model_json, &json_path);
            pb_json.inc(1);
            pb_json.finish_with_message("✓ JSON");
            result
        });

        // Wait for all exports to complete
        let result_ply = handle_ply
            .join()
            .map_err(|_| anyhow::anyhow!("PLY export thread panicked"))?;
        let result_safetensors = handle_safetensors
            .join()
            .map_err(|_| anyhow::anyhow!("safetensors export thread panicked"))?;
        let result_gltf = handle_gltf
            .join()
            .map_err(|_| anyhow::anyhow!("glTF export thread panicked"))?;
        let result_json = handle_json
            .join()
            .map_err(|_| anyhow::anyhow!("JSON export thread panicked"))?;

        // Return first error if any
        result_ply?;
        result_safetensors?;
        result_gltf?;
        result_json?;
    } else {
        // No progress bars - export sequentially
        export_ply(model, &output_dir.join("model.ply"))?;
        export_safetensors(model, &output_dir.join("model.safetensors"))?;
        export_gltf(model, &output_dir.join("model.gltf"), true)?;
        export_json_checkpoint(model, &output_dir.join("model.json"))?;
    }

    Ok(())
}
